from typing import Optional, Tuple
import torch
import torch.nn as nn
import torch.nn.functional as F

try:
    from ncps.torch import CfC
except ImportError:
    raise ImportError("ncps package is required. Please install it with `pip install ncps`.")


class CfCLiquidUNet1D(nn.Module):
    """
    1D Continuous-Time Liquid U-Net Core using Closed-form Continuous-time (CfC) layers.
    
    This module is designed to receive an array/sequence of embedding vectors 
    (batch_size, seq_len, in_features) generated by an autoencoder encoder.
    
    Architecture:
    - Contracting path (Encoder): Multi-scale temporal feature extraction with CfC blocks and 1D downsampling.
    - Bottleneck: Deep continuous-time CfC layer capturing long-range spatio-temporal storm dynamics.
    - Expanding path (Decoder): Temporal upsampling, multi-scale skip connections, and CfC synthesis blocks.
    """
    def __init__(
        self,
        in_features: int = 64,
        hidden_dims: Tuple[int, int, int] = (64, 128, 256),
        backbone_units: int = 64,
        backbone_layers: int = 1,
        mode: str = "default",
        dropout: float = 0.1
    ):
        super(CfCLiquidUNet1D, self).__init__()
        c1, c2, c3 = hidden_dims
        self.in_features = in_features
        self.hidden_dims = hidden_dims
        
        # =========================================================================
        # 1. Contracting Path (Encoder)
        # =========================================================================
        # Level 1
        self.enc_cfc1 = CfC(
            in_features, c1, 
            batch_first=True, return_sequences=True,
            backbone_units=backbone_units, backbone_layers=backbone_layers, mode=mode
        )
        self.enc_norm1 = nn.LayerNorm(c1)
        self.down1 = nn.Conv1d(c1, c2, kernel_size=3, stride=2, padding=1)
        
        # Level 2
        self.enc_cfc2 = CfC(
            c2, c2, 
            batch_first=True, return_sequences=True,
            backbone_units=backbone_units, backbone_layers=backbone_layers, mode=mode
        )
        self.enc_norm2 = nn.LayerNorm(c2)
        self.down2 = nn.Conv1d(c2, c3, kernel_size=3, stride=2, padding=1)
        
        # =========================================================================
        # 2. Bottleneck (Deep Liquid Core)
        # =========================================================================
        self.bottleneck_cfc = CfC(
            c3, c3, 
            batch_first=True, return_sequences=True,
            backbone_units=backbone_units, backbone_layers=backbone_layers, mode=mode
        )
        self.bottleneck_norm = nn.LayerNorm(c3)
        self.dropout = nn.Dropout(dropout)
        
        # =========================================================================
        # 3. Expanding Path (Decoder with Skip Connections)
        # =========================================================================
        # Level 2 Decoder
        self.up2_proj = nn.Conv1d(c3, c2, kernel_size=1)
        self.dec_cfc2 = CfC(
            c2 + c2, c2, 
            batch_first=True, return_sequences=True,
            backbone_units=backbone_units, backbone_layers=backbone_layers, mode=mode
        )
        self.dec_norm2 = nn.LayerNorm(c2)
        
        # Level 1 Decoder
        self.up1_proj = nn.Conv1d(c2, c1, kernel_size=1)
        self.dec_cfc1 = CfC(
            c1 + c1, c1, 
            batch_first=True, return_sequences=True,
            backbone_units=backbone_units, backbone_layers=backbone_layers, mode=mode
        )
        self.dec_norm1 = nn.LayerNorm(c1)
        
        self.out_dim = c1

    def forward(
        self, 
        embeddings: torch.Tensor, 
        timespans: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        """
        Forward pass through the CfC Liquid U-Net Core receiving embedding vectors.
        
        Parameters
        ----------
        embeddings : torch.Tensor
            Array of embedding vectors of shape (batch_size, seq_len, in_features).
        timespans : Optional[torch.Tensor]
            Optional time elapsed between time steps for continuous-time ODE dynamics.
            
        Returns
        -------
        torch.Tensor
            Liquid U-Net processed sequence tensor of shape (batch_size, seq_len, out_dim).
        """
        # Ensure 3D sequence shape (batch_size, seq_len, in_features)
        if embeddings.dim() == 2:
            embeddings = embeddings.unsqueeze(1)
            
        # -------------------------------------------------------------
        # Level 1 Encoder
        # -------------------------------------------------------------
        e1, _ = self.enc_cfc1(embeddings, timespans=timespans)
        e1 = self.enc_norm1(F.relu(e1))  # (B, T, c1)
        
        # Downsample Level 1 -> Level 2
        e1_t = e1.transpose(1, 2)       # (B, c1, T)
        d1 = self.down1(e1_t).transpose(1, 2)  # (B, T_down1, c2)
        
        # -------------------------------------------------------------
        # Level 2 Encoder
        # -------------------------------------------------------------
        e2, _ = self.enc_cfc2(d1)
        e2 = self.enc_norm2(F.relu(e2))  # (B, T_down1, c2)
        
        # Downsample Level 2 -> Bottleneck
        e2_t = e2.transpose(1, 2)       # (B, c2, T_down1)
        d2 = self.down2(e2_t).transpose(1, 2)  # (B, T_down2, c3)
        
        # -------------------------------------------------------------
        # Bottleneck (Deep Liquid Core)
        # -------------------------------------------------------------
        b, _ = self.bottleneck_cfc(d2)
        b = self.bottleneck_norm(F.relu(b))
        b = self.dropout(b)             # (B, T_down2, c3)
        
        # -------------------------------------------------------------
        # Level 2 Decoder (with Skip Connection from e2)
        # -------------------------------------------------------------
        b_t = b.transpose(1, 2)         # (B, c3, T_down2)
        # Upsample temporal dimension to match e2's sequence length
        u2 = F.interpolate(b_t, size=e2.size(1), mode='nearest')
        u2 = self.up2_proj(u2).transpose(1, 2)  # (B, T_down1, c2)
        
        # Skip Connection: Concatenate along feature dimension
        cat2 = torch.cat([u2, e2], dim=-1)      # (B, T_down1, c2 + c2)
        d_out2, _ = self.dec_cfc2(cat2)
        d_out2 = self.dec_norm2(F.relu(d_out2)) # (B, T_down1, c2)
        
        # -------------------------------------------------------------
        # Level 1 Decoder (with Skip Connection from e1)
        # -------------------------------------------------------------
        d_out2_t = d_out2.transpose(1, 2)       # (B, c2, T_down1)
        # Upsample temporal dimension to match original sequence length T
        u1 = F.interpolate(d_out2_t, size=e1.size(1), mode='nearest')
        u1 = self.up1_proj(u1).transpose(1, 2)  # (B, T, c1)
        
        # Skip Connection: Concatenate along feature dimension
        cat1 = torch.cat([u1, e1], dim=-1)      # (B, T, c1 + c1)
        d_out1, _ = self.dec_cfc1(cat1)
        d_out1 = self.dec_norm1(F.relu(d_out1)) # (B, T, c1)
        
        return d_out1

    def extract_latest_state(self, seq_features: torch.Tensor) -> torch.Tensor:
        """
        Extracts the latest temporal observation (index -1) from the U-Net sequence.
        
        Parameters
        ----------
        seq_features : torch.Tensor
            Processed sequence of shape (batch_size, seq_len, out_dim).
            
        Returns
        -------
        torch.Tensor
            Aggregated state vector of shape (batch_size, out_dim).
        """
        return seq_features[:, -1, :]


if __name__ == "__main__":
    print("Testing CfCLiquidUNet1D receiving embedding vector array...")
    unet = CfCLiquidUNet1D(in_features=64, hidden_dims=(64, 128, 256))
    sample_embeddings = torch.randn(8, 6, 64)
    unet_out = unet(sample_embeddings)
    print(f"Embeddings in: {sample_embeddings.shape} --> UNet sequence out: {unet_out.shape}")
    assert unet_out.shape == (8, 6, 64)
    state = unet.extract_latest_state(unet_out)
    print(f"Extracted latest state shape: {state.shape}")
    assert state.shape == (8, 64)
    print("CfCLiquidUNet1D tests passed!")
